name: selective tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true  # Cancel old runs

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: false

      - name: Run pre-commit
        run: uvx pre-commit run --all-files --show-diff-on-failure

  selective-test:
    runs-on: linux-x86-n4-16
    container: us-docker.pkg.dev/ml-oss-artifacts-published/ml-public-container/ml-build:latest
    env:
      UV_HTTP_TIMEOUT: 300
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: false

      - name: Setup Python and Venv
        run: |
          uv python install 3.12
          uv venv

      - name: Install dependencies
        run: uv pip install .[testing]

      - name: Run Selective Tests
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          uv run python scripts/run_selective_tests.py